AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    MemorySize: 256

Resources:
  NasdaqNewsScraperLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: NasdaqNewsScraperLambda
      Handler: com.vai.news.lambda.NasdaqNewsScraperLambda::handleRequest
      Runtime: java8
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        Scrape:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /scrape
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  NasdaqScraperApi:
    Description: "API Gateway endpoint URL for Prod stage for News Scraping function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/scrape/"
  NasdaqNewsScraperLambda:
    Description: "News Scraping Lambda Function's ARN"
    Value: !GetAtt NasdaqNewsScraperLambda.Arn
  NasdaqNewsScraperLambdaIamRole:
    Description: "Implicit IAM Role created for News Scraping function"
    Value: !GetAtt NasdaqNewsScraperLambdaRole.Arn
